# Generated by Django 6.0 on 2025-12-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_categoria', models.CharField(max_length=100, unique=True, verbose_name='categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_lugar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_lugar', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_objeto', models.CharField(max_length=100, unique=True, verbose_name='objeto')),
                ('objeto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.categoriaobjeto', verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField()),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('P', 'Pendiente'), ('M', 'Malo')], max_length=1)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='objetos_lugar', to='p_w_pvsa.lugar', verbose_name='lugar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anterior', models.SmallIntegerField()),
                ('estado_anterior', models.CharField(choices=[('B', 'Bueno'), ('P', 'Pendiente'), ('M', 'Malo')], max_length=1)),
                ('detalle_anterior', models.CharField(blank=True, max_length=200)),
                ('fecha_anterior', models.DateField()),
                ('objeto_del_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicoobjeto', to='p_w_pvsa.objetolugar', verbose_name='objeto del lugar')),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.piso', verbose_name='piso'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='lugar_tipo_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.tipolugar', verbose_name='tipo de lugar'),
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='marca')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='material')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.objeto', verbose_name='objeto')),
            ],
        ),
        migrations.AddField(
            model_name='objetolugar',
            name='tipo_de_objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='objetos_lugar', to='p_w_pvsa.tipoobjeto', verbose_name='tipo de objeto'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100, unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.sector', verbose_name='sector')),
            ],
        ),
        migrations.AddField(
            model_name='piso',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.ubicacion', verbose_name='ubicacion'),
        ),
    ]
