# Generated by Django 6.0 on 2025-12-31 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLugarObjetoTipico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('tipo_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipicos', to='p_w_pvsa.tipolugar', verbose_name='tipo de lugar')),
                ('tipo_objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipico_en', to='p_w_pvsa.tipoobjeto', verbose_name='tipo de objeto')),
            ],
            options={
                'ordering': ('orden', 'id'),
                'unique_together': {('tipo_lugar', 'tipo_objeto')},
            },
        ),
    ]
